### PR TITLE
Seeds

### PR DESCRIPTION
**Pull request by policiacaro**
I tested it super quickly on my machine and it makes the comments correctly, its just assigning them to a different incident. before it was 1, 2, and 4, and now its just the i being passed in the 3.times do, so incident 1, incident 2, incident 3

### CODE REVIEW

**Comment by nogawa11** [comment]
Hey! Thanks for this, but I actually changed it to only assign to 1, 2, and 4 (can_receive_comments = true) because 3 and 5 are supposed to disable comments since not all incidents are supposed to take comments!

**Comment by policiacaro** [comment]
i dun goofed then, ill rewrite it so it only assigns to those incidents. thank you for the heads up!

**Comment by policiacaro** [comment]
@nogawa11 oki doki its been fixed, I just did rails c and checked every comment and they are only appearing on incidents 1, 2 & 4

**Comment by nogawa11** [comment]
@policiacaro I'm so sorry!! can you push this code again tomorrow morning? I made a mistake with the gemfile and I'm too afraid to merge it now!

**Pull request closed without merging**
